import type { Metadata } from "next";
import "./globals.css";
import { montserrat, poppins } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${montserrat.variable} ${poppins.variable} font-poppins`}>
        {children}
      </body>
    </html>
  );
}
